### ISSUE TITLE
Wrong date in exported GPX

### ISSUE THREAD

**Issue by paulgodard** [labexp/osmtracker-android#343] opened 2022-11-07 09:53 UTC
I have been using OSMTracker for Android for many years with no issue.

I am currently traveling in Angola and creating a track log every day. When the track log is named it has the correct date but when it is closed and I open it, the date recorded inside is totally wrong. For example, for a track log is created on 7 nov 2022, the date inside is 24 mar 2003! (see a [tracklog gpx](https://www.paulgodard.com/public/assets/tracks/2022-11-05_18-07-26_2022-11-05_18-07-26.gpx))

I need to change the inside date in order to match with photos taken at the same time. How can I do that? I urgently need to find a way to do that… please help me.

I also would like to see how I can correct this issue. So please help me there too.

**Comment by ulrike-k** [comment] 2024-12-04 19:44
I have a similar issue, but in the other direction. The exported date in the gpx file is fine, but when I take pictures in the OSMTracker for Android, they get a wrong date. Example here from a waypoint with a picture today, 2024-12-04. The foto date and time was set on 2005-04-20:
<wpt lat="45.82652331351823" lon="16.027750526646795">
		<ele>176.2255644133115</ele>
		<time>2024-12-04T08:48:12Z</time>
		<name><![CDATA[Photo (8.0m)]]></name>
		<cmt><![CDATA[compass heading: 289.7724609375deg
			compass accuracy: 3]]></cmt>
		<link href="2005-04-20_10-48-14.jpg">
			<text>2005-04-20_10-48-14.jpg</text>
		</link>
		<sat>15</sat>
		<hdop>2.0</hdop>
	</wpt>
I can not figure out, if this is an issue of OSMtracker for Android (v2024.07.09) or of my mobile phone (Samsung Galaxy S10, Android 9.0).  I am also very happily and satisfied using this App for many years, and the problem occured first time in september this year, when the storage place of the exported data changed to Android/data/net.osmtracker/files/osmtracker instead of being before directly in the internal storage. 
Does anybody has an idea how to solve this? Thanks in advance!

**Comment by Andyporras** [comment] 2024-12-05 12:18
Hi @paulgodard, thank you for reporting this issue and providing detailed examples. I wanted to let you know that this bug has been fixed in the current developer version of OSMTracker. If you are interested, you can test the developer version to verify that the issue is resolved. Please let me know if you need guidance on how to access it.

**Comment by Andyporras** [comment] 2024-12-05 12:43
Likewise, here is the apk, of the current version of the developer branch: 
[app-debug.zip](https://github.com/user-attachments/files/18023324/app-debug.zip)

**Comment by ulrike-k** [comment] 2024-12-06 08:46
> Likewise, here is the apk, of the current version of the developer branch: [app-debug.zip](https://github.com/user-attachments/files/18023324/app-debug.zip)

Hi @Andyporras, thank you for your feedback. I tried to install the developer version you sent, but after successful start of the installation unfortunately I get only the error message "App not installed".

**Comment by jer194** [comment] 2024-12-06 11:52
Probably you need to uninstall the old version first; see also: https://github.com/labexp/osmtracker-android/issues/466

**Comment by ulrike-k** [comment] 2024-12-07 09:44
Thank you, @jer194. Since I have hundreds of OSM-tracker tracks and special button layouts on my mobile, I installed the developer version for the test on another phone. And I can happily confirm that the issue with the wrong date on the pictures is solved :). 
Great that you also implemented back that the exported gpx file including the pictures is saved in internal storage/documents and not anymore in Andoid/data/net.osmtracker/files. Now they appear after export again in the gallery which wasn't the case in the version v2024.07.09. On the other hand it seems, that the pictures are now in the newest version saved in both places. 
However, thank you for the help, my issue is solved!

**Comment by Andyporras** [comment] 2024-12-07 12:38
I am glad that the changes made to the application have been useful, I will keep trying to fix these small bugs in the future, with the help of the other contributors of the project, if you have any other problem, please communicate it to fix it before the new version is released.

**Comment by Andyporras** [comment] 2024-12-07 12:50
Hi @ulrike-k , thank you for confirming that the issue with the wrong date on pictures is resolved and for testing the developer version on another phone. I am glad that the changes made to the application have been useful, I will keep trying to fix these small bugs in the future, with the help of the other contributors of the Project, Please feel free to share any additional feedback or concerns. I'm happy to help!

**Comment by Binnette** [comment] 2024-12-16 22:13
Close as fixed in develop.

**Closed by Binnette** 2024-12-16 22:13 UTC
Labels: type:bug, scope:export, prio:high, good first issue
