### ISSUE TITLE
No maps in background

### ISSUE THREAD

**Issue by kudlav** [labexp/osmtracker-android#212] opened 2019-06-18 22:05 UTC
Background maps are not displayed.
I tried Mapnik, Cycle Map, MapQuest Open.
SM-A300FU - Android 6.0.1
APP 0.7.1

Previous issue #194 was closed, but it seems to be not solved yet, so I'm creating new issue.

**Comment by canfe** [comment] 2019-06-19 10:10
I confirm, until now (19/06/2019) the problem has not been solved.
No app updates on the Playstore.

**Comment by xsaco07** [comment] 2019-06-20 20:22
Hello @kudlav and @canfe, thanks for being aware of the background map issue. 

Effectively there is not an update ready yet but the problem was fixed and is currently merged in develop branch. If you want to check it out, the pull request that solved the issue is this one #203
 
This issue and others are part of the next milestone for version 0.7.2. It is almost finished, so watch for the next update.

Thanks again!

**Comment by AlainKnaff** [comment] 2019-06-21 08:21
Any idea of when this will be available in the stores?

Unfortunately, I can't compile the github version as I get the error below (without explanation *how* to accept these licenses...):

Thanks

> ./gradlew build

> Configure project :app 
Checking the license for package Android SDK Build-Tools 28.0.3 in /home/alain/Projects/Osmtracker/android-studio/licenses
Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.
Checking the license for package Android SDK Platform 27 in /home/alain/Projects/Osmtracker/android-studio/licenses
Warning: License for package Android SDK Platform 27 not accepted.


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     platforms;android-27 Android SDK Platform 27
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
  
  Using Android SDK: /home/alain/Projects/Osmtracker/android-studio

**Comment by EmmanuelAB** [comment] 2019-07-02 20:37
This looks like a different problem, Would you mind to create another issue with that compilation problem . And we'll close this one related to the background map (It'll be fixed in the 0.7.2 version).

**Closed by EmmanuelAB** 2019-07-02 20:37 UTC
