### ISSUE TITLE
Cycle map says API key required

### ISSUE THREAD

**Issue by jidanni** [labexp/osmtracker-android#96] opened 2017-05-16 13:01 UTC
In settings choose Cycle Map as the tile source. The background of the image seen says API key required.

**Comment by jidanni** [comment] 2017-05-16 13:03
And choosing MapQuest Open doesn't even show any tiles at all, at least for Taiwan

**Comment by nguillaumin** [comment] 2017-05-16 16:42
Interesting. I'm using [OSMDroid](https://github.com/osmdroid/osmdroid) for the map background, perhaps something has changed regarding access to the Cycle Map / MapQuest

**Comment by jperryhouts** [comment] 2017-06-20 17:38
I got the same error, but then I zoomed the map way out and back in to my location and it works fine now.

In my case it was just after I installed the app and it hadn't locked a satellite yet, so it thought I was past the north pole, which also might have been Antarctica for some reason.

**Comment by EmmanuelAB** [comment] 2019-07-02 16:29
Isn't this issue duplicated of #125 ?

**Comment by jperryhouts** [comment] 2019-07-02 16:34
If anything that's a duplicate of this issue. It was opened almost a year later than this one.

**Comment by EmmanuelAB** [comment] 2019-07-02 21:30
Now the app can only use Mapnik as tile provider (since it's the only working without a key). Then Cycle Map is not even choosable. This issue will be closed.

**Closed by EmmanuelAB** 2019-07-02 21:30 UTC
Labels: bug, map-view
