### ISSUE TITLE
Error 500: Internal Server Error when upload GPX data to OSM

### ISSUE THREAD

**Issue by adissadis** [labexp/osmtracker-android#137] opened 2018-05-22 02:31 UTC
Hi OSMTracker Developer,

I got some issue when I tried to upload GPX data to OSM. It said that "Unable to authenticate to OSM.......internal server error".

Not sure why this happen but I think it related to OSM change their http into https. Because I got same error like this in our local tasking manager version 2.

Hopefully this screenshot will help you guys:

![whatsapp image 2018-05-22 at 9 24 06 am](https://user-images.githubusercontent.com/2520159/40339062-c22c5b58-5da2-11e8-8f99-a52569fb075b.jpeg)

My colleagues also got this error since a week ago.

Thank you..

**Comment by Inyaheyukan** [comment] 2018-05-22 17:42
Me too.

**Comment by openbrian** [comment] 2018-05-24 13:41
I have this issue too.  I need to upload tracks for the San Diego Zoo.

Indeeed, OSMTracker calls http not https.  (https://github.com/labexp/osmtracker-android/blob/master/app/src/main/java/org/osmtracker/osm/OpenStreetMapConstants.java#L8)

**Comment by hikaruAi** [comment] 2018-05-26 18:05
Same issue here

**Comment by jidanni** [comment] 2018-05-26 22:03
For me the app just totally crashes when I try to upload a track These days. The only walk around is to export to GPX and upload the track manually on the website form.

**Comment by cstackpole** [comment] 2018-05-27 03:35
@jidanni I think that if you go into settings and "Reset OSM authentication" then when you try to upload you will get this error message. Mine did the same thing where it just crashed the first two times and I thought it was due to bad wifi connection. After I did the reset is when I got this message.

**Comment by cstackpole** [comment] 2018-05-31 01:49
Bump please? I've got a lot of tracks to uploaded fixes into OSM and doing them one by one via export is draining me. :-) Thanks!

**Comment by EmmanuelAB** [comment] 2018-06-01 20:31
Thanks for reporting the issue, we're already working to fix it.

**Comment by jidanni** [comment] 2018-06-08 12:27
So the project is unmaintained. Anybody have suggestions for an alternate?

**Comment by jamescr** [comment] 2018-06-12 01:35
Our team is assuming the maintenance of the project and this bug unfortunately happened in the midst of the transition. 

The original osmtracker developer transferred us the repo only after changing the application package name and the signing key for the play store. Both decisions are completely understandable on his behalf. The problem is that in order to post a bug fix we need to publish a new app rather than an update. This means that users' unpublished traces could be lost.

The bug fix is in progress and it'll be published as v0.6.12 as soon as possible. To get it, it'll be necessary to install the app again. You'll need to export the traces on your current install and push them manually into OSM. 

There will be no need to uninstall your current version to install the new one.

**Comment by aton1698** [comment] 2018-06-21 17:57
We have created a beta version that solves this issue and it's available on [Google play](https://play.google.com/apps/testing/net.osmtracker). We'll keep working on some new functionalities for osmtracker. 
If anyone finds some issue, please [let us know](https://github.com/labexp/osmtracker-android/issues).

**Comment by cstackpole** [comment] 2018-06-21 20:46
For those of us who do not have access to Google Play, is there any chance it will go to F-Droid? Or just the final release?
Thanks for this hard work!

**Comment by jamescr** [comment] 2018-07-06 20:16
@cstackpole Yes we will upload the 6.0.12 version and latter updates. I'll let you know when is uploaded.

**Closed** 2018-07-06 22:06 UTC
Labels: bug

**Comment by jamescr** [comment] 2018-07-06 22:40
The request for inclusion in Fdroid:  https://gitlab.com/fdroid/fdroiddata/merge_requests/3402

**Comment by cstackpole** [comment] 2018-08-08 12:01
@jamescr 
Sorry to bump the old closed thread, but would you please take another look at the fdroid status?
https://gitlab.com/fdroid/fdroiddata/merge_requests/3402

After sitting for a month, there is finally activity! :-)

Thank you.

**Comment by sushilkrcse** [comment] 2019-07-12 08:31
I got "Server error (500) when I login in OPEN SOURCE MANO, using username 'admin' & password 'admin'. So what is actual problem & how I resolve it
