### ISSUE TITLE
Add device identifier to gpx tracks

### ISSUE THREAD

**Issue by jer194** [labexp/osmtracker-android#470] opened 2024-12-02 16:46 UTC
I'm using several devices (for fun), and tracks from different hardware are of different quality sometimes.

Is it possile to add info about the recording device into the <metadata> section,
like (from 'getprop'):

[ro.product.vendor.manufacturer]: [Xiaomi]
[ro.product.vendor.model]: [Redmi Note 8T]
[ro.product.vendor.name]: [willow]

Also, when exporting tracks, it would be nice to be able to add some user specified identifier to the track name.

**Comment by jer194** [comment] 2024-12-02 19:05
Thanks, that's a good solution as well for me
(though I'd rather prefer something like yyyyMMdd-hhmmss_EXPORT_LABEL.gpx, 
to keep the sorting by time).

**Comment by Binnette** [comment] 2024-12-03 13:04
Duplicate of #333

**Closed by Binnette** 2024-12-03 13:04 UTC
Labels: type:enhancement, prio:normal

**Comment by Kevin-Salazar-itcr** [comment] 2024-12-10 03:22
Hi @jer194, @Binnette!
* in PR #483 
I’ve implemented a new feature enabling customized suffix labels for GPX files during file sharing.
