### ISSUE TITLE
Name field not encoded in GPX file

### ISSUE THREAD

**Issue by lgommans** [labexp/osmtracker-android#327] opened 2021-12-30 05:56 UTC
When exporting a GPX file whose `<name>` contains an `&` symbol, the file will contain that character literally, e.g.:

```
<?xml version="1.0" encoding="UTF-8" ?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" version="1.1" creator="OSMTracker for Android™ - https://github.com/labexp/osmtracker-android" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd ">
    <metadata>
        <name>some & name</name>
[...]
```

This crashes when trying to upload the GPX file to OpenStreetMap:

![ruby stack trace reporting an error on line 4](https://user-images.githubusercontent.com/5626710/147725320-335790d3-bbb7-463f-9b16-5d5cb38d812f.png)
<sub>(I censored a few fields because I didn't ask the user who reported this whether it was okay to share these details, and they are of no relevance that I can see.)</sub>

Or when trying to open it in JOSM:

`Could not read file 'xyz.gpx'. Error is: The entity name must immediately follow the '&' in the entity reference (at line 4, column 45). The file was created by "OSMTracker for Android™ - https://github.com/labexp/osmtracker-android"`

By manually changing the `&` to an `&amp;` (I just did that in Vim), the file opens correctly in JOSM.

The user whose file this is, reports that they only edited the name inside of OSMTracker, i.e. they did not manually insert the character in the XML. It would seem that the `name` field is not correctly encoded when writing the file.

**Comment by lgommans** [comment] 2021-12-30 06:09
I had a peek at the code (I like the file structuring, it was super easy to find the relevant code!)

This seems to be the broken part: https://github.com/labexp/osmtracker-android/blob/master/app/src/main/java/net/osmtracker/gpx/ExportTrackTask.java#L311

A few lines down, the track description and keywords are also affected.

A simple fix would be to add CDATA tags (since users are unlikely to type those) or to disallow using `<>&` and perhaps other special XML characters; a full fix would be to do escaping.

**Comment by Binnette** [comment] 2024-11-22 22:07
Close as duplicate of #313

**Closed by Binnette** 2024-11-22 22:07 UTC
