### ISSUE TITLE
Button produces unknown message

### ISSUE THREAD

**Issue by jidanni** [labexp/osmtracker-android#122] opened 2018-01-13 09:09 UTC
I am offline. At the top of the screen there is a button. On the button there is a square with an arrow curving upwards and to the right. If I push the button some message appears in the middle of the screen very fast and then disappears. That is all I know.

**Comment by EmmanuelAB** [comment] 2019-05-31 20:57
Hi, this happens in the screen that appears when you tap a finished track. 
- If you hold that button, a little tooltip appears saying `Export as GPX` that is the function of that button
- The problem is that that export happens so fast that the message that appears ("Preparing export") can be barely read.

**Comment by EmmanuelAB** [comment] 2019-07-02 21:34
A possible solution could be showing a Toast after the exporting process finishes to explain what happened.

**Comment by xsaco07** [comment] 2020-01-31 20:31
![](https://github.trello.services/images/mini-trello-icon.png) [Button produces unknown message](https://trello.com/c/90xpB1au/42-button-produces-unknown-message)

**Comment by xsaco07** [comment] 2020-02-17 18:22
This issue was fixed in pr #229

**Closed by xsaco07** 2020-02-17 18:22 UTC
Labels: enhancement, needs-pr, ux
